'use strict';
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const { execFileSync } = require('node:child_process');
const { chromium } = require('playwright');
const base = process.env.PREVIEW_URL || 'https://127.0.0.1:9445';
const state = process.env.PREVIEW_STATE || path.resolve(__dirname, '../.preview');
const db = path.join(state, 'mock.sqlite3');
const python = process.env.DATASETS_PYTHON || 'python3';
let browser;
let restoreCaptions;
const captionState = episode => ({ instruction: episode.instruction,
  review_flag: !!episode.review_flag, crop: episode.crop ?? null,
  review_reason: episode.review_reason || '',
  subtasks: episode.subtasks.map(cue => ({ start: cue.start, end: cue.end, text: cue.text ?? cue.desc })),
  atomic: episode.atomic.map(cue => ({ start: cue.start, end: cue.end, text: cue.text })) });
const grantAdmin = enabled => execFileSync(python, ['-c',
  "import sqlite3,sys; c=sqlite3.connect(sys.argv[1]); c.execute(\"INSERT OR IGNORE INTO user_roles VALUES ('mock-worker','admin')\" if sys.argv[2]=='1' else \"DELETE FROM user_roles WHERE user_id='mock-worker' AND role='admin'\"); c.commit(); c.close()",
  db, enabled ? '1' : '0']);

(async () => {
  assert.ok(fs.existsSync(db));
  browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ ignoreHTTPSErrors: true, hasTouch: true });
  const anonymous = await context.request.get(`${base}/captioning_data/`, { maxRedirects: 0 });
  assert.equal(anonymous.status(), 302);
  assert.equal(anonymous.headers().location, '/?next=/captioning_data/');
  assert.equal((await context.request.get(`${base}/captioning_data/api/episodes`)).status(), 401);
  assert.equal((await context.request.post(`${base}/api/auth/web/login`, { data: { email: 'worker', password: 'wrong' } })).status(), 401);
  const page = await context.newPage();
  const errors = []; page.on('pageerror', error => { errors.push(error.message); console.error(error.stack); });
  await page.goto(`${base}/captioning_data/`);
  await page.locator('#login-button:not([disabled])').waitFor();
  await page.locator('#identifier').fill('worker'); await page.locator('#password').fill('preview-password'); await page.locator('#login-button').click();
  await page.waitForURL(`${base}/captioning_data/**`);
  await page.locator('#edSave').waitFor({ timeout: 60000 });
  assert.equal(await page.title(), 'Project1B · captioning_data');
  assert.equal((await context.request.get(`${base}/api/admin/videos`)).status(), 403);
  const user = await (await context.request.get(`${base}/api/auth/me`)).json();
  assert.equal(user.user_id, 'mock-worker'); assert.deepEqual(user.roles, ['worker']);
  const checkQAProgress = async () => {
    await page.locator('#edSave').waitFor();
    assert.equal(await page.locator('#qaStats').isVisible(), true);
    await page.evaluate(() => {
      window.qaProgressOriginal = { EPS, ROSTER, CUR, FILTERED, ME, who: $('#whoSel').value, open: $('#qaStats').open };
      const episode = { ...CUR, duration: 8 };
      EPS = [{ ...episode, assignee: 'QA reviewer fixture', qa: 'corrected', review_flag: true },
        { ...episode, id: 'qa-confirmed-fixture', assignee: 'QA admin fixture', qa: 'confirmed', review_flag: true },
        { ...episode, id: 'qa-pending-fixture', assignee: 'QA reviewer fixture', qa: null }];
      CUR = EPS[0]; FILTERED = EPS;
      ROSTER = { reviewers: ['QA reviewer fixture', 'QA admin fixture'], admins: ['QA admin fixture'] };
      showMe(); $('#qaStats').open = true;
    });
    const reviewer = await page.evaluate(() => ME.role === 'reviewer');
    assert.deepEqual(await page.locator('#qaStatsBody tr.qa').evaluateAll(rows => rows.map(row => row.dataset.who)),
      reviewer ? ['QA reviewer fixture'] : ['QA reviewer fixture', 'QA admin fixture']);
    assert.deepEqual(await page.locator('#qaStatsBody tr.all td.num').allTextContents(),
      reviewer ? ['2', '0.0 h', ' 1', '0.00 h', ' 0', '0.00 h', '1', '50%']
        : ['3', '0.0 h', ' 1', '0.00 h', ' 1', '0.00 h', '1', '67%']);
    await page.locator('#qaStatsBody tr[data-who="QA reviewer fixture"]').click();
    assert.equal(await page.locator('#whoSel').inputValue(), 'QA reviewer fixture');
    assert.deepEqual(await page.evaluate(() => FILTERED.map(episode => episode.qa)), ['corrected', null]);
    await page.evaluate(() => { ME = null; showMe(); });
    assert.equal(await page.locator('#qaStats').isHidden(), true);
    assert.equal(await page.locator('#qaStatsBody').innerHTML(), '');
    await page.evaluate(() => {
      const original = window.qaProgressOriginal;
      ({ EPS, ROSTER, CUR, FILTERED, ME } = original);
      showMe(); $('#whoSel').value = original.who; $('#qaStats').open = original.open; applyFilter();
      delete window.qaProgressOriginal;
    });
  };
  await checkQAProgress();
  const checkLandingDefaults = async () => {
    const endpoint = `${base}/captioning_data/api/episodes`;
    await page.route(endpoint, async route => {
      const response = await route.fetch(), data = await response.json();
      const episode = data.episodes[0], name = data.user.name;
      data.episodes = [{ ...episode, assignee: name },
        { ...episode, id: 'landing-admin-fixture', assignee: 'Other admin' },
        { ...episode, id: 'landing-reviewer-fixture', assignee: 'Other reviewer' }];
      data.roster = { reviewers: ['Other reviewer', ...(data.user.role === 'admin' ? [] : [name])],
        admins: ['Other admin', ...(data.user.role === 'admin' ? [name] : [])] };
      await route.fulfill({ response, json: data });
    });
    try {
      await page.goto(`${base}/captioning_data/`); await page.locator('#edSave').waitFor();
      assert.equal(await page.locator('#whoSel').inputValue(), '@me');
      assert.deepEqual(await page.evaluate(() => FILTERED.map(episode => episode.assignee)),
        [await page.evaluate(() => ME.name)]);
      assert.equal(await page.locator('#captionCompare').isHidden(), true);
      assert.equal(await page.locator('#compareBtn').getAttribute('aria-expanded'), 'false');
      await page.locator('#whoSel').selectOption('');
      assert.equal(await page.evaluate(() => FILTERED.length), 3);
      await page.locator('#whoSel').selectOption('@me');
      assert.equal(await page.evaluate(() => FILTERED.length), 1);
      await page.locator('#compareBtn').click();
      assert.equal(await page.locator('#captionCompare').isVisible(), true);
      await page.reload(); await page.locator('#edSave').waitFor();
      assert.equal(await page.locator('#whoSel').inputValue(), '@me');
      assert.equal(await page.locator('#captionCompare').isHidden(), true);
    } finally {
      await page.unroute(endpoint);
      await page.goto(`${base}/captioning_data/`); await page.locator('#edSave').waitFor();
    }
  };
  await checkLandingDefaults();
  try {
    grantAdmin(true);
    assert.ok((await (await context.request.get(`${base}/api/auth/me`)).json()).roles.includes('admin'));
    assert.equal((await context.request.get(`${base}/api/admin/videos`)).status(), 200);
  } finally { grantAdmin(false); }
  assert.equal((await context.request.get(`${base}/api/admin/videos`)).status(), 403);
  const id = await page.evaluate(() => CUR.id);
  const version = await page.evaluate(() => EDIT.version);
  const initial = await (await context.request.get(`${base}/captioning_data/api/episode?p=${encodeURIComponent(id)}`)).json();
  let lastTestVersion = initial.version;
  restoreCaptions = async () => {
    await context.request.post(`${base}/api/auth/web/login`, { data: { email: 'worker', password: 'preview-password' } });
    const current = await (await context.request.get(`${base}/captioning_data/api/episode?p=${encodeURIComponent(id)}`)).json();
    if (JSON.stringify(captionState(current)) === JSON.stringify(captionState(initial))) return;
    if (current.version !== lastTestVersion) { console.log('Concurrent preview correction preserved.'); return; }
    const cookie = (await context.cookies()).find(cookie => cookie.name === '__Host-rbt_csrf');
    const restored = await context.request.post(`${base}/captioning_data/api/${initial.edited ? 'edit' : 'revert'}`, {
      data: { id, version: current.version, ...captionState(initial) }, headers: { Origin: base, 'X-CSRF-Token': cookie.value }
    });
    assert.equal(restored.status(), 200, 'Restore initial preview captions');
  };
  const media = await context.request.get(`${base}/captioning_data/video?p=${encodeURIComponent(id)}`, { headers: { Range: 'bytes=0-31' } });
  assert.equal(media.status(), 206); assert.equal((await media.body()).length, 32);
  await page.waitForFunction(() => document.querySelector('video')?.readyState > 0, null, { timeout: 30000 });
  const mediaLayout = () => page.evaluate(() => {
    const rect = selector => {
      const box = document.querySelector(selector).getBoundingClientRect();
      return { x: box.x, y: box.y, right: box.right, bottom: box.bottom, width: box.width };
    };
    return { video: rect('#videos'), comparison: rect('#captionCompare') };
  });
  assert.equal(await page.locator('#captionCompare').isHidden(), true);
  assert.equal(await page.locator('#captionCompare > summary').count(), 0);
  assert.equal(await page.locator('#compareBtn').getAttribute('aria-expanded'), 'false');
  const controls = selector => page.locator(selector).evaluate(group => [...group.querySelectorAll('button, input, select')].map(control => control.id));
  assert.deepEqual(await controls('.cams'), ['cc', 'qwenToggle', 'captionSettingsBtn', 'videoSize', 'rate']);
  assert.deepEqual(await controls('.tlbar'), ['edMode', 'reset', 'compareBtn', 'reviewFlag', 'link', 'magnet', 'edDiscard', 'edSave']);
  assert.equal(await page.locator('#annotationToggle, #fs').count(), 0);
  assert.equal(await page.locator('#selbox').isVisible(), true);
  assert.ok(await page.locator('#selbox').evaluate(card => card.getBoundingClientRect().height <= 96));
  assert.equal(await page.locator('#selbox').evaluate(card => card.nextElementSibling.classList.contains('tlrow')), true);
  await page.locator('.review-media').evaluate(media => media.scrollIntoView({ block: 'start' }));
  assert.ok(await page.evaluate(() => {
    const view = document.querySelector('#view').getBoundingClientRect(), video = document.querySelector('#videos').getBoundingClientRect(), timeline = document.querySelector('.tlrow').getBoundingClientRect();
    return video.top >= view.top - 1 && timeline.bottom <= view.bottom + 1;
  }), 'Video and full timeline fit together at 1280×720');
  await page.locator('#compareBtn').click();
  const wide = await mediaLayout();
  assert.ok(wide.comparison.x >= wide.video.right + 10);
  assert.ok(Math.abs(wide.comparison.y - wide.video.y) < 1);
  await page.locator('#compareBtn').click();
  assert.equal(await page.locator('#captionCompare').isHidden(), true);
  assert.equal(await page.locator('#compareBtn').getAttribute('aria-expanded'), 'false');
  assert.ok((await mediaLayout()).video.width > wide.video.width);
  await page.evaluate(initial => { EDIT = null; renderView(CUR, initial, 0); }, initial);
  assert.equal(await page.locator('#captionCompare').isHidden(), true);
  await page.locator('#compareBtn').click();
  assert.equal(await page.locator('#compareBtn').getAttribute('aria-expanded'), 'true');
  await page.waitForFunction(() => document.querySelector('video')?.readyState > 0);
  await page.setViewportSize({ width: 1000, height: 720 });
  const narrow = await mediaLayout();
  assert.ok(narrow.comparison.y >= narrow.video.bottom + 10);
  assert.ok(await page.locator('.review-media').evaluate(element => element.scrollWidth <= element.clientWidth + 1));
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.locator('video').focus(); await page.keyboard.press('f');
  await page.waitForFunction(() => document.fullscreenElement?.id === 'stage');
  assert.ok(await page.locator('#stage').evaluate(element => element.getBoundingClientRect().width >= innerWidth - 1));
  const setCaptionOpacity = async value => {
    await page.locator('#captionOpacity').evaluate((input, value) => { input.value = value; input.dispatchEvent(new Event('input')); }, String(value));
    assert.equal(await page.locator('#captionOpacityValue').textContent(), `${value}%`);
    assert.equal(await page.locator('#captionOpacity').getAttribute('aria-valuetext'), `${value}%`);
    for (const selector of ['#ovlSub', '#ovlAtom']) {
      const style = await page.locator(selector).evaluate(element => ({ background: getComputedStyle(element).backgroundColor, opacity: getComputedStyle(element).opacity, color: getComputedStyle(element).color }));
      const alpha = value === 100 ? 'rgb(0, 0, 0)' : `rgba(0, 0, 0, ${value / 100})`;
      assert.equal(style.background, alpha); assert.equal(style.opacity, '1'); assert.equal(style.color, 'rgb(255, 255, 255)');
    }
  };
  await setCaptionOpacity(0);
  await setCaptionOpacity(100);
  await setCaptionOpacity(35);
  await page.evaluate(() => document.exitFullscreen());
  assert.equal(await page.locator('#captionSize').isHidden(), true);
  assert.equal(await page.locator('#captionWidth').isHidden(), true);
  assert.equal(await page.locator('#captionOpacity').isHidden(), true);
  await page.locator('#captionSettingsBtn').click();
  await page.waitForFunction(() => document.querySelector('#captionSettings').matches(':popover-open'));
  assert.equal(await page.locator('#captionSize').isVisible(), true);
  assert.equal(await page.locator('#captionWidth').isVisible(), true);
  assert.equal(await page.locator('#captionOpacity').isVisible(), true);
  const setCaptionSize = async value => {
    await page.locator('#captionSize').evaluate((input, value) => { input.value = value; input.dispatchEvent(new Event('input')); }, String(value));
    assert.equal(await page.locator('#captionSizeValue').textContent(), `${value}%`);
    assert.equal(await page.locator('#captionSize').getAttribute('aria-valuetext'), `${value}%`);
    assert.equal(await page.locator('#ovlSub').evaluate(element => parseFloat(getComputedStyle(element).fontSize)), 17 * value / 100);
    assert.equal(await page.locator('#ovlAtom').evaluate(element => parseFloat(getComputedStyle(element).fontSize)), 16 * value / 100);
  };
  await setCaptionSize(50); await setCaptionSize(200); await setCaptionSize(150);
  const setCaptionWidth = async value => {
    const draft = await page.evaluate(() => JSON.stringify(EDIT));
    await page.locator('#captionWidth').evaluate((input, value) => { input.value = value; input.dispatchEvent(new Event('input')); }, String(value));
    assert.equal(await page.locator('#captionWidthValue').textContent(), `${value}%`);
    assert.equal(await page.locator('#captionWidth').getAttribute('aria-valuetext'), `${value}%`);
    await page.waitForFunction(value => {
      const frame = document.querySelector('#stage').getBoundingClientRect(), box = document.querySelector('#ovl').getBoundingClientRect();
      return Math.abs(box.width - frame.width * value / 100) < 1;
    }, value);
    assert.ok(await page.locator('#ovl').evaluate(box => box.scrollWidth <= box.clientWidth + 1));
    assert.ok(await page.evaluate(value => [...document.querySelector('video').textTracks[0].cues].every(cue => cue.size === value), value));
    assert.equal(await page.evaluate(() => JSON.stringify(EDIT)), draft);
  };
  await setCaptionWidth(100); await setCaptionWidth(20); await setCaptionWidth(70);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#captionSettings').isHidden(), true);
  await page.locator('#captionSettingsBtn').click();
  await page.locator('#captionSettingsBtn').click();
  assert.equal(await page.locator('#captionSettings').isHidden(), true);
  await page.locator('#captionSettingsBtn').click();
  await page.locator('.title').click();
  assert.equal(await page.locator('#captionSettings').isHidden(), true);
  await page.reload(); await page.locator('#edSave').waitFor();
  assert.equal(await page.locator('#captionOpacity').inputValue(), '35');
  assert.equal(await page.locator('#captionSize').inputValue(), '150');
  assert.equal(await page.locator('#captionWidth').inputValue(), '70');
  assert.equal(await page.locator('#ovlAtom').evaluate(element => getComputedStyle(element).fontSize), '24px');
  assert.equal(await page.locator('#ovlAtom').evaluate(element => getComputedStyle(element).backgroundColor), 'rgba(0, 0, 0, 0.35)');
  await page.locator('#captionSettingsBtn').click();
  await setCaptionOpacity(72); await setCaptionSize(100); await setCaptionWidth(94);
  await page.keyboard.press('Escape');
  await page.waitForFunction(() => document.querySelector('video')?.readyState > 0);
  const captionsInside = () => page.waitForFunction(() => {
    const frame = document.querySelector('#stage').getBoundingClientRect(), box = document.querySelector('#ovl').getBoundingClientRect();
    return box.left >= frame.left - 1 && box.top >= frame.top - 1 && box.right <= frame.right + 1 && box.bottom <= frame.bottom + 1;
  }, null, { timeout: 3000 }).then(result => result.jsonValue());
  const dragCaptions = async (x, y) => {
    const box = await page.locator('#ovlAtom').boundingBox();
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
    await page.mouse.down(); await page.mouse.move(x, y, { steps: 5 }); await page.mouse.up();
  };
  await page.evaluate(() => document.querySelector('video').pause());
  const timeBeforeDrag = await page.locator('video').evaluate(video => video.currentTime);
  const frame = await page.locator('#stage').boundingBox();
  await dragCaptions(frame.x - 100, frame.y - 100);
  assert.ok(await captionsInside());
  assert.deepEqual(await page.evaluate(() => CAPTION_POS), [0, 0]);
  await dragCaptions(frame.x + frame.width + 100, frame.y + frame.height + 100);
  assert.ok(await captionsInside());
  assert.deepEqual(await page.evaluate(() => CAPTION_POS), [1, 1]);
  await setCaptionWidth(20); assert.ok(await captionsInside());
  await setCaptionWidth(100); assert.ok(await captionsInside());
  await setCaptionWidth(70); assert.ok(await captionsInside());
  assert.equal(await page.locator('video').evaluate(video => video.paused), true);
  assert.equal(await page.locator('video').evaluate(video => video.currentTime), timeBeforeDrag);
  await page.locator('#ovl').focus(); await page.keyboard.press('Home');
  assert.equal(await page.evaluate(() => CAPTION_POS), null);
  const home = await page.locator('#ovl').boundingBox();
  await page.keyboard.press('ArrowUp');
  assert.ok((await page.locator('#ovl').boundingBox()).y < home.y);
  const position = await page.evaluate(() => CAPTION_POS);
  await page.reload(); await page.locator('#edSave').waitFor();
  await page.waitForFunction(() => document.querySelector('video')?.readyState > 0);
  assert.deepEqual(await page.evaluate(() => CAPTION_POS), position);
  assert.ok(await captionsInside());
  await page.locator('#videoSize').evaluate(input => { input.value = '50'; input.dispatchEvent(new Event('input')); });
  await page.waitForFunction(() => document.querySelector('#videos').style.width === '50%');
  assert.ok(await captionsInside());
  await page.locator('video').focus(); await page.keyboard.press('f');
  await page.waitForFunction(() => document.fullscreenElement?.id === 'stage');
  await setCaptionWidth(70);
  assert.ok(await captionsInside());
  await page.evaluate(() => document.exitFullscreen());
  await setCaptionWidth(94);
  await page.locator('#videoSize').evaluate(input => { input.value = '100'; input.dispatchEvent(new Event('input')); });
  await page.locator('#cc').uncheck(); assert.equal(await page.locator('#ovl').isHidden(), true);
  await page.locator('#cc').check(); assert.ok(await captionsInside());
  const touch = await context.newCDPSession(page), touchBox = await page.locator('#ovlAtom').boundingBox();
  const point = { x: touchBox.x + touchBox.width / 2, y: touchBox.y + touchBox.height / 2 };
  await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [point] });
  await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: point.x, y: point.y - 40 }] });
  await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  assert.ok(await captionsInside());
  assert.ok((await page.locator('#ovlAtom').boundingBox()).y < touchBox.y);
  await touch.detach();
  await page.locator('#ovlAtom').dblclick();
  assert.equal(await page.evaluate(() => CAPTION_POS), null);
  const duration = initial.duration;
  const fixture = { ...initial, instruction: 'Instruction fixture',
    subtasks: [{ i: 0, start: 0, end: duration * 0.75, desc: 'Subtask fixture' }],
    atomic: [{ start: 0, end: duration * 0.25, text: '[both hands] First action' },
      { start: duration * 0.375, end: duration * 0.5, text: '[both hands] Second action' }] };
  const qwenFixture = { ...fixture,
    check: { ...fixture.check, task: { old: fixture.instruction, new: 'Suggested instruction', error: 'incorrect', saw: 'The person moves the object onto the table.' } },
    subtasks: fixture.subtasks.map(sub => ({ ...sub, check: { old: sub.desc, new: 'Suggested subtask', error: 'incorrect', saw: 'Both hands hold the object. <img src=x onerror=alert(1)>' } })) };
  await page.evaluate(fixture => renderView(CUR, fixture, 0), qwenFixture);
  await page.waitForFunction(() => document.querySelector('video')?.readyState > 0);
  assert.ok(await page.locator('#selChk .chk').count());
  assert.equal(await page.locator('#selChk img').count(), 0);
  assert.ok(await page.locator('#selChk').evaluate(card => card.scrollHeight <= card.clientHeight + 1));
  assert.ok(await page.locator('#selChk .chk-head').evaluateAll(headers => headers.every(header => {
    const verdict = header.firstElementChild.getBoundingClientRect(), saw = header.querySelector('.saw').getBoundingClientRect();
    return saw.left >= verdict.right && Math.abs(saw.top - verdict.top) < 2;
  })), 'Saw sentences share the verdict/error header row');
  await page.locator('#selChk').screenshot({ path: path.join(state, 'captioning-data-qwen-card.png') });
  const sideOpen = await page.evaluate(() => !document.body.classList.contains('noside'));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => showSide(false));
  assert.ok(await page.locator('#selChk').evaluate(card => card.scrollHeight <= card.clientHeight + 1 && card.scrollWidth <= card.clientWidth + 1));
  await page.locator('#selChk').screenshot({ path: path.join(state, 'captioning-data-qwen-card-mobile.png') });
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.evaluate(open => showSide(open), sideOpen);
  assert.ok(await page.locator('#levels [data-op="sugg"], #levels [data-op="sugg-ins"]').count());
  const beforeToggle = await page.evaluate(() => JSON.stringify(EDIT));
  await page.getByRole('button', { name: 'Hide Qwen suggestions', exact: true }).click();
  const qwenHidden = async () => {
    for (const element of await page.locator('#view .chk, #selChk, #view [data-op="sugg"], #view [data-op="sugg-ins"]').all()) {
      assert.equal(await element.isHidden(), true);
    }
  };
  await qwenHidden();
  assert.equal(await page.evaluate(() => JSON.stringify(EDIT)), beforeToggle);
  await page.locator('#selIn').fill('[both hands] Editing with suggestions hidden');
  assert.equal(await page.locator('#levels tr[data-l="atoms"][data-k="0"] .tx').inputValue(), '[both hands] Editing with suggestions hidden');
  await qwenHidden();
  await page.evaluate(fixture => { EDIT = null; renderView(CUR, fixture, 0); }, qwenFixture);
  await page.locator('.tlbar label.switch').click();
  await qwenHidden();
  await page.locator('.tlbar label.switch').click();
  await page.reload();
  await page.getByRole('button', { name: 'Show Qwen suggestions', exact: true }).waitFor();
  await page.evaluate(fixture => { EDIT = null; renderView(CUR, fixture, 0); }, qwenFixture);
  await qwenHidden();
  await page.getByRole('button', { name: 'Show Qwen suggestions', exact: true }).click();
  assert.equal(await page.locator('#selChk').isVisible(), true);
  assert.equal(await page.locator('#levels [data-op="sugg-ins"]').isVisible(), true);
  const qwenVersion = await page.evaluate(() => EDIT.version);
  const auditBeforeAccept = fs.readFileSync(path.join(state, 'edits.jsonl'), 'utf8');
  const acceptSubtask = page.locator('#selChk button[data-op="sugg"][data-l="subs"][data-k="0"]');
  assert.equal(await page.locator('#selIn').inputValue(), '[both hands] First action');
  await acceptSubtask.click();
  assert.equal(await page.evaluate(() => EDIT.subs[0].text), 'Suggested subtask');
  assert.equal(await page.locator('#levels tr[data-l="subs"][data-k="0"] input.tx').inputValue(), 'Suggested subtask');
  assert.equal(await page.locator('#ovlSub').innerText(), 'Suggested subtask');
  assert.match(await page.locator('#laneSub [data-sub="0"]').innerText(), /Suggested subtask/);
  assert.equal(await page.locator('#selIn').inputValue(), '[both hands] First action');
  assert.equal(await acceptSubtask.count(), 0);
  await page.keyboard.press('Control+z');
  assert.equal(await acceptSubtask.isVisible(), true);
  await page.locator('#laneSub [data-sub="0"]').click();
  await page.waitForFunction(() => !document.querySelector('video').seeking);
  await acceptSubtask.click();
  assert.equal(await page.locator('#selIn').inputValue(), 'Suggested subtask');
  await page.keyboard.press('Control+z');
  await page.locator('#selChk button[data-op="sugg-ins"]').click();
  assert.equal(await page.evaluate(() => EDIT.ins), 'Suggested instruction');
  assert.equal(await page.locator('#selIn').inputValue(), 'Subtask fixture');
  assert.equal(await page.locator('#levels input[data-l="ins"]').inputValue(), 'Suggested instruction');
  assert.equal(await page.locator('#laneIns').innerText(), 'Suggested instruction');
  assert.ok(await page.evaluate(() => [...document.querySelector('video').textTracks[0].cues].some(cue => cue.text === 'Suggested instruction')));
  await page.keyboard.press('Control+z');
  await page.locator('video').focus(); await page.keyboard.press('ArrowUp');
  assert.equal(await page.locator('#selIn').inputValue(), 'Instruction fixture');
  await page.locator('#selChk button[data-op="sugg-ins"]').click();
  assert.equal(await page.locator('#selIn').inputValue(), 'Suggested instruction');
  assert.equal(await page.locator('#selChk button[data-op="sugg-ins"]').count(), 0);
  await page.keyboard.press('Control+z');
  assert.equal(await page.evaluate(() => EDIT.version), qwenVersion);
  assert.equal(fs.readFileSync(path.join(state, 'edits.jsonl'), 'utf8'), auditBeforeAccept);
  await page.evaluate(fixture => { EDIT = null; renderView(CUR, fixture, 0); }, qwenFixture);
  await page.locator('.tlbar label.switch').click();
  assert.equal(await page.locator('#selChk button').count(), 0);
  assert.equal(await page.locator('#selParentIn').count(), 0);
  await page.locator('.tlbar label.switch').click();
  const parentFixture = { ...qwenFixture, subtasks: [
    { i: 0, start: 0, end: duration * 0.25, desc: 'First parent', check: { old: 'First parent', new: 'First parent suggestion', error: 'incorrect' } },
    { i: 1, start: duration * 0.25, end: duration * 0.75, desc: 'Second parent', check: { old: 'Second parent', new: 'Second parent suggestion', error: 'incorrect' } }] };
  await page.evaluate(fixture => { EDIT = null; renderView(CUR, fixture, 0); }, parentFixture);
  await page.waitForFunction(() => document.querySelector('video')?.readyState > 0);
  await page.locator('#levels tr[data-l="atoms"][data-k="1"] input.tx').focus();
  assert.equal(await page.locator('#selIn').inputValue(), '[both hands] Second action');
  assert.equal(await page.locator('#selParentIn').inputValue(), 'Second parent');
  if (await page.locator('#captionCompare').isHidden()) await page.locator('#compareBtn').click();
  await page.locator('#selParentIn').fill('Inline second parent');
  await page.locator('#selParentIn').pressSequentially(' correction');
  assert.equal(await page.locator('#selParentIn').evaluate(input => input === document.activeElement), true);
  assert.equal(await page.locator('#selIn').inputValue(), '[both hands] Second action');
  assert.equal(await page.evaluate(() => EDIT.subs[1].text), 'Inline second parent correction');
  assert.equal(await page.evaluate(() => EDIT.subs[0].text), 'First parent');
  assert.equal(await page.locator('#levels tr[data-l="subs"][data-k="1"] input.tx').inputValue(), 'Inline second parent correction');
  assert.match(await page.locator('#laneSub [data-sub="1"]').innerText(), /Inline second parent correction/);
  assert.ok(await page.evaluate(() => [...document.querySelector('video').textTracks[0].cues].some(cue => cue.text === 'Inline second parent correction')));
  assert.match(await page.locator('#cmpContent').innerText(), /Inline second parent correction/);
  assert.equal(await page.locator('#ovlSub').innerText(), 'First parent');
  await page.keyboard.press('Control+z');
  assert.equal(await page.locator('#selParentIn').inputValue(), 'Second parent');
  await page.locator('video').focus(); await page.locator('#selParentIn').focus();
  await page.keyboard.press('Space'); await page.keyboard.press('e'); await page.keyboard.press('p');
  assert.equal(await page.locator('video').evaluate(video => video.paused), true);
  assert.equal(await page.evaluate(() => EDIT.subs[1].start), duration * 0.25);
  await page.keyboard.press('Control+z');
  await page.locator('#selChk button[data-op="sugg"][data-k="1"]').click();
  assert.equal(await page.evaluate(() => EDIT.subs[1].text), 'Second parent suggestion');
  assert.equal(await page.evaluate(() => EDIT.subs[0].text), 'First parent');
  assert.equal(await page.locator('#selIn').inputValue(), '[both hands] Second action');
  assert.equal(await page.locator('#selParentIn').inputValue(), 'Second parent suggestion');
  await page.locator('#levels tr[data-l="subs"][data-k="0"] input.tx').focus();
  assert.equal(await page.locator('#selParentIn').inputValue(), 'Instruction fixture');
  await page.locator('#selParentIn').fill('Inline instruction correction');
  assert.equal(await page.locator('#selIn').inputValue(), 'First parent');
  assert.equal(await page.locator('#levels input[data-l="ins"]').inputValue(), 'Inline instruction correction');
  assert.equal(await page.locator('#laneIns').innerText(), 'Inline instruction correction');
  assert.ok(await page.evaluate(() => [...document.querySelector('video').textTracks[0].cues].some(cue => cue.text === 'Inline instruction correction')));
  assert.match(await page.locator('#cmpContent').innerText(), /Inline instruction correction/);
  await page.keyboard.press('Control+z');
  assert.equal(await page.locator('#selParentIn').inputValue(), 'Instruction fixture');
  const parentSideOpen = await page.evaluate(() => !document.body.classList.contains('noside'));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => showSide(false));
  assert.ok(await page.locator('#selParentIn').evaluate(input => input.getBoundingClientRect().width > 250));
  assert.ok(await page.locator('#selbox').evaluate(card => card.scrollWidth <= card.clientWidth + 1));
  await page.locator('#selbox').screenshot({ path: path.join(state, 'captioning-data-parent-editor-mobile.png') });
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.evaluate(open => showSide(open), parentSideOpen);
  const selectionFixture = { ...fixture, subtasks: [
    { i: 0, start: 0, end: duration * 0.25, desc: 'Selected subtask fixture' },
    { i: 1, start: duration * 0.25, end: duration * 0.75, desc: 'Next subtask fixture' }] };
  await page.evaluate(fixture => { EDIT = null; renderView(CUR, fixture, 0); }, selectionFixture);
  await page.waitForFunction(() => document.querySelector('video')?.readyState > 0);
  await page.locator('#laneSub [data-sub="0"]').click();
  await page.waitForFunction(() => !document.querySelector('video').seeking);
  assert.equal(await page.locator('#selIn').inputValue(), 'Selected subtask fixture');
  await page.locator('video').focus(); await page.keyboard.press('Enter');
  assert.equal(await page.locator('#selIn').inputValue(), 'Selected subtask fixture');
  await page.locator('#selIn').fill('Manual subtask correction');
  assert.equal(await page.locator('#levels tr[data-l="subs"][data-k="0"] input.tx').inputValue(), 'Manual subtask correction');
  assert.equal(await page.locator('#ovlSub').innerText(), 'Manual subtask correction');
  assert.match(await page.locator('#laneSub [data-sub="0"]').innerText(), /Manual subtask correction/);
  assert.equal(await page.evaluate(() => EDIT.atoms[0].text), '[both hands] First action');
  await page.keyboard.press('Control+z'); await page.keyboard.press('Escape');
  await page.evaluate(() => document.querySelector('video').play());
  await page.waitForFunction(() => document.querySelector('#selIn')?.value === '[both hands] First action');
  await page.evaluate(() => { const video = document.querySelector('video'); video.pause(); video.currentTime = video.duration * 0.1; });
  await page.waitForFunction(() => !document.querySelector('video').seeking);
  await page.locator('#levels tr[data-l="subs"][data-k="1"] input.tx').focus();
  assert.equal(await page.locator('#selIn').inputValue(), 'Next subtask fixture');
  await page.locator('#selIn').fill('Future subtask correction');
  assert.equal(await page.evaluate(() => EDIT.subs[1].text), 'Future subtask correction');
  assert.equal(await page.locator('#ovlSub').innerText(), 'Selected subtask fixture');
  await page.keyboard.press('Control+z'); await page.keyboard.press('Escape');
  await page.locator('#levels tr[data-l="subs"][data-k="0"] input.tx').focus();
  await page.locator('video').focus(); await page.keyboard.press('e');
  assert.equal(await page.evaluate(() => EDIT.subs[0].end), Math.round(duration * 0.1 * 10) / 10);
  assert.equal(await page.evaluate(() => EDIT.atoms[0].end), duration * 0.25);
  await page.keyboard.press('Control+z');
  await page.evaluate(() => { const video = document.querySelector('video'); video.currentTime = video.duration * 0.4; });
  await page.waitForFunction(() => !document.querySelector('video').seeking);
  await page.locator('#levels tr[data-l="subs"][data-k="1"] input.tx').focus();
  await page.locator('video').focus(); await page.keyboard.press('p');
  assert.equal(await page.evaluate(() => EDIT.subs[0].end), Math.round(duration * 0.4 * 10) / 10);
  assert.equal(await page.evaluate(() => EDIT.subs[1].start), Math.round(duration * 0.4 * 10) / 10);
  assert.equal(await page.evaluate(() => EDIT.atoms[1].start), duration * 0.375);
  await page.keyboard.press('Control+z');
  const beforeO = await page.evaluate(() => JSON.stringify(EDIT));
  await page.keyboard.press('o');
  assert.equal(await page.evaluate(() => JSON.stringify(EDIT)), beforeO);
  assert.equal(await page.locator('#guide kbd').filter({ hasText: /^o$/ }).count(), 0);
  await page.evaluate(() => { EDIT = null; });
  await page.evaluate(fixture => renderView(CUR, fixture, 0), fixture);
  await page.waitForFunction(() => document.querySelector('video')?.readyState > 0);
  await page.locator('#selIn').fill('[both hands] ' + 'move the item carefully '.repeat(30));
  await setCaptionWidth(20);
  assert.ok(await page.locator('#ovlAtom').evaluate(box => {
    const style = getComputedStyle(box), padding = parseFloat(style.paddingTop) + parseFloat(style.paddingBottom);
    return box.getBoundingClientRect().height > parseFloat(style.lineHeight) + padding;
  }), 'Long captions wrap within narrowed box');
  assert.ok(await captionsInside());
  await setCaptionWidth(94);
  await page.locator('#videoSize').evaluate(input => { input.value = '25'; input.dispatchEvent(new Event('input')); });
  assert.ok(await captionsInside());
  await page.keyboard.press('Control+z');
  await page.locator('#videoSize').evaluate(input => { input.value = '100'; input.dispatchEvent(new Event('input')); });
  assert.ok(await captionsInside());
  const seek = async time => page.evaluate(time => {
    const video = document.querySelector('video'); video.pause(); video.currentTime = time;
    video.dispatchEvent(new Event('timeupdate'));
  }, time);
  await seek(duration * 0.1); await page.locator('video').focus();
  await page.evaluate(() => document.querySelector('video').play());
  await page.waitForFunction(() => !document.querySelector('video').paused);
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('video').evaluate(video => video.paused), true);
  assert.equal(await page.locator('#selIn').evaluate(input => input === document.activeElement), true);
  assert.equal(await page.locator('#selIn').inputValue(), '[both hands] First action');
  await page.locator('#selIn').dispatchEvent('keydown', { key: 'ArrowUp', isComposing: true });
  assert.equal(await page.locator('#selIn').inputValue(), '[both hands] First action');
  await page.keyboard.press('ArrowUp');
  assert.equal(await page.locator('#selIn').inputValue(), 'Subtask fixture');
  await page.locator('#selIn').fill('Keyboard subtask correction');
  assert.equal(await page.locator('#levels tr[data-l="subs"][data-k="0"] input.tx').inputValue(), 'Keyboard subtask correction');
  assert.equal(await page.locator('#ovlSub').innerText(), 'Keyboard subtask correction');
  assert.ok((await page.locator('#laneSub [data-sub="0"]').getAttribute('title')).includes('Keyboard subtask correction'));
  assert.equal(await page.evaluate(() => EDIT.atoms[0].text), '[both hands] First action');
  await page.keyboard.press('Control+z');
  await page.keyboard.press('ArrowUp');
  assert.equal(await page.locator('#selIn').inputValue(), 'Instruction fixture');
  await page.locator('#selIn').fill('Keyboard instruction correction');
  assert.equal(await page.locator('#levels input[data-l="ins"]').inputValue(), 'Keyboard instruction correction');
  assert.equal(await page.locator('#laneIns').innerText(), 'Keyboard instruction correction');
  await page.keyboard.press('ArrowUp');
  assert.equal(await page.locator('#selIn').inputValue(), 'Keyboard instruction correction');
  await page.keyboard.press('Control+z');
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('#selIn').evaluate(input => input === document.activeElement), false);
  await page.evaluate(() => document.querySelector('video').play());
  await page.waitForFunction(() => document.querySelector('#selIn')?.value === '[both hands] First action');
  await page.evaluate(() => document.querySelector('video').pause());
  await seek(duration * 0.4);
  assert.equal(await page.locator('#selIn').inputValue(), '[both hands] Second action');
  page.once('dialog', dialog => dialog.accept());
  await page.locator('.tlbar label.switch').click();
  assert.equal(await page.locator('#edMode').isChecked(), false);
  await page.locator('video').focus(); await page.keyboard.press('Enter');
  assert.equal(await page.locator('#edMode').isChecked(), true);
  assert.equal(await page.locator('#selbox').isVisible(), true);
  assert.equal(await page.locator('#selIn').evaluate(input => input === document.activeElement), true);
  assert.equal(await page.locator('#selIn').inputValue(), '[both hands] Second action');
  await page.keyboard.press('Escape');
  await page.evaluate(fixture => renderView(CUR, { ...fixture, subtasks: [], instruction: '' }, 0), fixture);
  await page.waitForFunction(() => document.querySelector('video')?.readyState > 0);
  await page.locator('video').focus(); await page.keyboard.press('Enter'); await page.keyboard.press('ArrowUp');
  assert.equal(await page.locator('#selIn').inputValue(), '');
  await page.locator('#selIn').fill('Added instruction through keyboard');
  assert.equal(await page.locator('#levels input[data-l="ins"]').inputValue(), 'Added instruction through keyboard');
  assert.equal(await page.locator('#laneIns').innerText(), 'Added instruction through keyboard');
  await page.evaluate(fixture => renderView(CUR, fixture, 0), fixture);
  await page.waitForFunction(() => document.querySelector('video')?.readyState > 0);
  const draft = () => page.evaluate(() => JSON.parse(JSON.stringify({ ins: EDIT.ins, subs: EDIT.subs, atoms: EDIT.atoms })));
  await seek(duration * 0.1);
  await page.locator('video').focus(); await page.keyboard.press('Enter');
  for (const [abbreviation, tag] of [['lh', '[left hand]'], ['rh', '[right hand]'], ['bh', '[both hands]']]) {
    await page.locator('#selIn').fill(abbreviation);
    await page.keyboard.press('End'); await page.keyboard.press('Space');
    assert.equal(await page.locator('#selIn').inputValue(), `${tag} `);
    assert.equal(await page.evaluate(() => EDIT.atoms[0].text), `${tag} `);
    assert.equal(await page.locator('video').evaluate(video => video.paused), true);
    await page.keyboard.press('Control+z');
    assert.equal(await page.locator('#selIn').inputValue(), abbreviation);
  }
  await page.locator('#selIn').fill('rhythm');
  await page.keyboard.press('End'); await page.keyboard.press('Space');
  assert.equal(await page.locator('#selIn').inputValue(), 'rhythm ');
  const twoHands = '[left hand] hold cup | [right hand] lift lid | [both hands] steady tray';
  await page.locator('#selIn').fill(twoHands);
  await page.locator('#selIn').evaluate(input => input.setSelectionRange(16, 16));
  await page.keyboard.press('Shift+Delete');
  const clearedHand = '[left hand] | [right hand] lift lid | [both hands] steady tray';
  assert.equal(await page.locator('#selIn').inputValue(), clearedHand);
  await page.locator('#selIn').dispatchEvent('keydown', { key: 'Delete', shiftKey: true, repeat: true });
  assert.equal(await page.locator('#selIn').inputValue(), clearedHand);
  assert.equal(await page.locator('#levels tr[data-l="atoms"][data-k="0"] input.tx').inputValue(), clearedHand);
  assert.match(await page.locator('#laneAtom').innerText(), /lift lid/);
  assert.match(await page.locator('#ovlAtom').innerText(), /lift lid/);
  await page.keyboard.press('Shift+Delete');
  assert.equal(await page.locator('#selIn').inputValue(), '[right hand] lift lid | [both hands] steady tray');
  await page.keyboard.press('Control+z');
  assert.equal(await page.locator('#selIn').inputValue(), clearedHand);
  await page.keyboard.press('Control+z');
  assert.equal(await page.locator('#selIn').inputValue(), twoHands);
  const swappedHands = '[right hand] hold cup | [left hand] lift lid | [both hands] steady tray';
  await page.keyboard.press('Alt+s');
  assert.equal(await page.locator('#selIn').inputValue(), swappedHands);
  assert.equal(await page.locator('#levels tr[data-l="atoms"][data-k="0"] input.tx').inputValue(), swappedHands);
  assert.ok(await page.evaluate(text => [...document.querySelector('video').textTracks[0].cues].some(cue => cue.text === text), swappedHands));
  await page.keyboard.press('Control+z');
  await page.locator('#selbox button[data-op="swap"]').click();
  assert.equal(await page.locator('#selIn').inputValue(), swappedHands);
  await page.locator('video').focus(); await page.keyboard.press('Alt+s');
  assert.equal(await page.locator('#selIn').inputValue(), twoHands);
  const tableCaption = page.locator('#levels tr[data-l="atoms"][data-k="0"] input.tx');
  await tableCaption.fill('bh'); await page.keyboard.press('End'); await page.keyboard.press('Space');
  assert.equal(await page.locator('#selIn').inputValue(), '[both hands] ');
  await tableCaption.fill(twoHands); await page.keyboard.press('Alt+s');
  assert.equal(await page.locator('#selIn').inputValue(), swappedHands);
  await page.locator('#selParentIn').fill('lh'); await page.keyboard.press('End'); await page.keyboard.press('Space');
  assert.equal(await page.evaluate(() => EDIT.subs[0].text), '[left hand] ');
  assert.equal(await page.evaluate(() => EDIT.atoms[0].text), swappedHands);
  const timeInput = page.locator('#levels tr[data-l="atoms"][data-k="0"] input.tm').first();
  await timeInput.focus(); const beforeTimeShortcut = await draft(); await page.keyboard.press('Alt+s');
  assert.deepEqual(await draft(), beforeTimeShortcut);
  await page.locator('video').focus(); await page.keyboard.press('Shift+Delete');
  assert.deepEqual(await draft(), beforeTimeShortcut);
  await page.evaluate(fixture => renderView(CUR, fixture, 0), fixture);
  await page.waitForFunction(() => document.querySelector('video')?.readyState > 0);
  await seek(duration * 0.1);
  await page.locator('video').focus();
  await page.keyboard.press('Space');
  await page.waitForFunction(() => !document.querySelector('video').paused);
  await page.evaluate(() => document.querySelector('video').dispatchEvent(new KeyboardEvent('keydown', { key: ' ', code: 'Space', repeat: true, bubbles: true })));
  assert.equal(await page.locator('video').evaluate(video => video.paused), false);
  await page.keyboard.press('Space');
  assert.equal(await page.locator('video').evaluate(video => video.paused), true);
  await seek(duration * 0.1);
  const originalDraft = await draft();
  await page.keyboard.press('e');
  assert.equal((await draft()).atoms[0].end, Math.round(duration * 0.1 * 10) / 10);
  assert.equal((await draft()).atoms.length, 2);
  assert.equal(await page.locator('#selIn').inputValue(), 'Subtask fixture');
  await page.keyboard.press('Control+z');
  assert.deepEqual(await draft(), originalDraft);
  await seek(duration * 0.4);
  await page.keyboard.press('p');
  const extended = await draft();
  assert.equal(extended.atoms[0].end, Math.round(duration * 0.4 * 10) / 10);
  assert.equal(extended.atoms[1].start, extended.atoms[0].end);
  assert.equal(extended.atoms[0].text, originalDraft.atoms[0].text);
  assert.equal(extended.atoms[1].text, originalDraft.atoms[1].text);
  assert.equal(await page.locator('#selIn').inputValue(), '[both hands] Second action');
  await page.keyboard.press('Control+z');
  assert.deepEqual(await draft(), originalDraft);
  await seek(duration * 0.499);
  await page.keyboard.press('p');
  assert.equal((await draft()).atoms[1].start, Math.round((duration * 0.5 - 0.1) * 10) / 10);
  await page.keyboard.press('Control+z');
  await seek(duration * 0.1);
  await page.keyboard.press('p');
  assert.deepEqual(await draft(), originalDraft);
  await seek(duration * 0.3);
  await page.keyboard.press('e');
  assert.equal((await draft()).subs[0].end, Math.round(duration * 0.3 * 10) / 10);
  assert.deepEqual((await draft()).atoms, originalDraft.atoms);
  await page.keyboard.press('Control+z');
  await seek(duration * 0.1);
  await page.locator('#selIn').focus();
  await page.keyboard.press('Space'); await page.keyboard.press('e'); await page.keyboard.press('p');
  assert.equal(await page.locator('video').evaluate(video => video.paused), true);
  assert.deepEqual((await draft()).atoms.map(x => [x.start, x.end]), originalDraft.atoms.map(x => [x.start, x.end]));
  await page.keyboard.press('Control+z');
  assert.deepEqual(await draft(), originalDraft);
  await page.locator('video').focus();
  assert.equal(await page.locator('#selIn').inputValue(), originalDraft.atoms[0].text);
  const synchronized = async (level, index, text) => {
    assert.equal(await page.locator('#selIn').inputValue(), text);
    assert.equal(await page.locator(`#levels tr[data-l="${level}"][data-k="${index}"] input.tx`).inputValue(), text);
    assert.ok((await page.locator(`#lane${level === 'atoms' ? 'Atom' : 'Sub'} [data-${level === 'atoms' ? 'atom' : 'sub'}="${index}"]`).getAttribute('title')).includes(text));
    assert.ok((await page.locator(level === 'atoms' ? '#ovlAtom' : '#ovlSub').innerText()).includes(text.replace('[both hands] ', '')));
    assert.ok(await page.evaluate(text => [...document.querySelector('video').textTracks[0].cues].some(cue => cue.text === text), text));
  };
  await seek(duration * 0.1);
  assert.equal(await page.locator('#selIn').inputValue(), '[both hands] First action');
  const atomicInput = page.locator('#levels tr[data-l="atoms"][data-k="0"] input.tx');
  await atomicInput.fill('[both hands] Edited in table');
  await synchronized('atoms', 0, '[both hands] Edited in table');
  await page.locator('#selIn').fill('[both hands] Edited in selected annotation');
  await page.locator('#selIn').pressSequentially(' live');
  await synchronized('atoms', 0, '[both hands] Edited in selected annotation live');
  await page.locator('#laneAtom [data-atom="0"]').dblclick();
  await page.locator('.tled').fill('[both hands] Edited on timeline');
  assert.equal(await page.locator('.tled').evaluate(input => input === document.activeElement), true);
  await synchronized('atoms', 0, '[both hands] Edited on timeline');
  await page.locator('.tled').press('Escape');
  await synchronized('atoms', 0, '[both hands] Edited in selected annotation live');
  await page.locator('#laneAtom [data-atom="0"]').dblclick();
  await page.locator('.tled').fill('[both hands] Timeline commit');
  await page.locator('.tled').press('Enter');
  await synchronized('atoms', 0, '[both hands] Timeline commit');
  await seek(duration * 0.25);
  assert.equal(await page.locator('#selIn').inputValue(), 'Subtask fixture');
  await page.locator('#selIn').fill('Edited fallback subtask');
  await synchronized('subs', 0, 'Edited fallback subtask');
  await seek(duration * 0.375);
  assert.equal(await page.locator('#selIn').inputValue(), '[both hands] Second action');
  await seek(duration * 0.1);
  assert.equal(await page.locator('#selIn').inputValue(), '[both hands] Timeline commit');
  await seek(duration * 0.2);
  await page.evaluate(() => document.querySelector('video').play());
  await page.waitForFunction(() => document.querySelector('#selIn')?.value === 'Edited fallback subtask');
  await page.evaluate(() => document.querySelector('video').pause());
  await seek(duration * 0.875);
  assert.equal(await page.locator('#selIn').inputValue(), 'Instruction fixture');
  await page.locator('#selIn').fill('Edited fallback instruction');
  assert.equal(await page.locator('#levels input[data-l="ins"]').inputValue(), 'Edited fallback instruction');
  assert.equal(await page.locator('#laneIns').innerText(), 'Edited fallback instruction');
  assert.equal(await page.locator('#ovlSub').innerText(), 'Edited fallback instruction');
  assert.ok(await page.evaluate(() => [...document.querySelector('video').textTracks[0].cues].some(cue => cue.text === 'Edited fallback instruction')));
  assert.equal(await page.locator('#selbox').isVisible(), true);
  await seek(duration * 0.4);
  assert.equal(await page.locator('#ovlAtom').isVisible(), true);
  assert.equal(await page.locator('#selIn').inputValue(), '[both hands] Second action');
  await seek(duration * 0.23);
  const movedEnd = page.locator('#levels tr[data-l="atoms"][data-k="0"] input[data-f="end"]');
  await movedEnd.fill(String(duration * 0.2)); await movedEnd.dispatchEvent('change');
  assert.equal(await page.locator('#selIn').inputValue(), '[both hands] Timeline commit');
  await seek(duration * 0.24);
  assert.equal(await page.locator('#selIn').inputValue(), 'Edited fallback subtask');
  page.once('dialog', dialog => dialog.accept());
  await page.locator('.tlbar label.switch').click();
  await seek(duration * 0.4);
  assert.match(await page.locator('#selTx').innerText(), /Second action/);
  await seek(duration * 0.3);
  assert.equal(await page.locator('#selTx').innerText(), 'Subtask fixture');
  await page.locator('.tlbar label.switch').click();
  await page.evaluate(initial => { store('selected-annotation', '0'); EDIT = null; renderView(CUR, initial, 0); }, initial);
  assert.equal(await page.locator('#annotationToggle').count(), 0);
  assert.equal(await page.locator('#selbox').isVisible(), true);
  await page.waitForFunction(() => document.querySelector('video')?.readyState > 0);
  await page.evaluate(() => document.querySelector('video').pause());
  if (await page.locator('#captionCompare').isHidden()) await page.locator('#compareBtn').click();
  const pairs = await page.evaluate(() => captionPairs(
    [{ start: 0, end: 1, text: 'A' }, { start: 1, end: 2, text: 'B' }],
    [{ start: 0, end: 1, text: 'A' }, { start: 1, end: 1.2, text: 'Added' }, { start: 1.2, end: 2, text: 'B' }]
  ).map(([before, after]) => [before?.text || null, after?.text || null]));
  assert.deepEqual(pairs, [['A', 'A'], [null, 'Added'], ['B', 'B']]);
  const end = page.locator('#levels tr[data-l="atoms"][data-k="0"] input[data-f="end"]');
  await end.fill(await page.evaluate(() => fmt(EDIT.atoms[0].end - 0.1))); await end.dispatchEvent('change');
  assert.match(await page.locator('#cmpContent').innerText(), /Timing changed/);
  page.once('dialog', dialog => dialog.accept()); await page.locator('#edDiscard').click();
  await page.locator('input[data-l="ins"]').fill('<img src=x onerror="window.captionCompareUnsafe=true">');
  assert.equal(await page.locator('#cmpContent img').count(), 0);
  assert.equal(await page.evaluate(() => !!window.captionCompareUnsafe), false);
  if (initial.subtasks.length) await page.locator('#levels tr[data-l="subs"][data-k="0"] input.tx').focus();
  else await page.locator('#levels tr[data-l="atoms"][data-k="0"] input.tx').focus();
  await page.locator('#selParentIn').fill('Local preview correction');
  assert.equal(await page.locator('#cmpAfter option[value="current"]').textContent(), 'Unsaved draft');
  await page.locator('#cmpBefore').selectOption('previous');
  assert.match(await page.locator('#cmpMeta').innerText(), /before selected change/i);
  assert.ok(await page.locator('#cmpContent ins').count()); assert.ok(await page.locator('#cmpContent del').count());
  await page.locator('.review-media').scrollIntoViewIfNeeded();
  assert.equal(await page.locator('#captionCompare').evaluate(element => getComputedStyle(element).overflowY), 'auto');
  await page.locator('.review-media').screenshot({ path: path.join(state, 'captioning-data-video-comparison.png') });
  await page.getByRole('button', { name: 'Flag for Review', exact: true }).click();
  await page.locator('#reviewReason').focus(); await page.keyboard.press('Control+s');
  assert.match(await page.locator('#edmsg').innerText(), /Write a reason/);
  assert.equal(await page.evaluate(() => EDIT.version), version);
  await page.locator('#reviewReason').fill('Hands are obscured; please verify this action.');
  assert.equal(await page.locator('#reviewFlag').getAttribute('aria-pressed'), 'true');
  assert.match(await page.locator('#cmpContent').innerText(), /Flagged for review/);
  await page.getByRole('button', { name: 'Remove Review Flag', exact: true }).click();
  await page.keyboard.press('Control+z');
  assert.equal(await page.evaluate(() => EDIT.review_flag), true);
  await page.locator('#cropTool > summary').click();
  await page.locator('#cropPreview').uncheck();
  const testCrop = { start: Math.floor(initial.duration * 0.25 * 10) / 10, end: Math.floor(initial.duration * 0.75 * 10) / 10 };
  await page.locator('video').evaluate((video, time) => { video.pause(); video.currentTime = time; }, testCrop.start);
  await page.getByRole('button', { name: 'Start at playhead', exact: true }).click();
  await page.locator('video').evaluate((video, time) => { video.currentTime = time; }, testCrop.end);
  await page.getByRole('button', { name: 'End at playhead', exact: true }).click();
  assert.deepEqual(await page.evaluate(() => EDIT.crop), testCrop);
  assert.match(await page.locator('#cmpContent').innerText(), /Video crop/);
  assert.ok(await page.locator('#cropLeft').evaluate(mask => parseFloat(mask.style.width) > 0));
  await page.getByRole('button', { name: 'Clear crop', exact: true }).click();
  assert.equal(await page.evaluate(() => EDIT.crop), null);
  await page.keyboard.press('Control+z');
  assert.deepEqual(await page.evaluate(() => EDIT.crop), testCrop);
  await page.locator('#cropStart').fill(String(testCrop.end)); await page.locator('#cropStart').dispatchEvent('change');
  assert.match(await page.locator('#edmsg').innerText(), /at least 0.1 s/);
  assert.deepEqual(await page.evaluate(() => EDIT.crop), testCrop);
  await page.locator('#cropPreview').check();
  await page.locator('video').evaluate(video => { video.currentTime = 0; });
  await page.waitForFunction(start => Math.abs(document.querySelector('video').currentTime - start) < 0.05, testCrop.start);
  await page.locator('video').evaluate(video => { video.currentTime = video.duration; });
  await page.waitForFunction(end => document.querySelector('video').paused && Math.abs(document.querySelector('video').currentTime - end) < 0.05, testCrop.end);
  await page.locator('#edSave').click();
  await page.waitForFunction(before => EDIT?.version === before + 1, version);
  lastTestVersion = version + 1;
  const records = fs.readFileSync(path.join(state, 'edits.jsonl'), 'utf8').trim().split('\n').map(JSON.parse);
  assert.equal(records.at(-1).editor_id, 'mock-worker'); assert.equal(records.at(-1).instruction, 'Local preview correction');
  assert.deepEqual(records.at(-1).editor_roles, ['worker']);
  assert.equal(records.at(-1).version, version + 1); assert.match(records.at(-1).source_sha256, /^[a-f0-9]{64}$/);
  assert.deepEqual(records.at(-1).before, captionState(initial));
  assert.deepEqual(records.at(-1).original, initial.original);
  assert.equal(records.at(-1).review_flag, true); assert.deepEqual(records.at(-1).crop, testCrop);
  assert.equal(await page.evaluate(() => CUR.qa), 'corrected');
  assert.equal(records.at(-1).review_reason, 'Hands are obscured; please verify this action.');
  await page.locator('#flagSel').selectOption('flagged for review');
  assert.ok(await page.evaluate(() => FILTERED.some(episode => episode.id === CUR.id)));
  await page.locator('#flagSel').selectOption('');
  await page.locator('#qaSel').selectOption('todo');
  assert.equal(await page.evaluate(() => FILTERED.some(episode => episode.id === CUR.id)), false);
  await page.locator('#qaSel').selectOption('');
  await page.reload(); await page.locator('#edSave').waitFor();
  assert.equal(await page.evaluate(() => EDIT.review_flag), true);
  assert.equal(await page.locator('#reviewReason').inputValue(), 'Hands are obscured; please verify this action.');
  assert.deepEqual(await page.evaluate(() => EDIT.crop), testCrop);
  const cookies = await context.cookies();
  const csrf = cookies.find(cookie => cookie.name === '__Host-rbt_csrf').value;
  const reverted = await context.request.post(`${base}/captioning_data/api/revert`, {
    data: { id, version: version + 1 }, headers: { Origin: base, 'X-CSRF-Token': csrf }
  });
  assert.equal(reverted.status(), 200);
  lastTestVersion = version + 2;
  await page.reload(); await page.locator('#edSave').waitFor();
  const savedHistory = await (await context.request.get(`${base}/captioning_data/api/episode?p=${encodeURIComponent(id)}`)).json();
  assert.equal(savedHistory.history.at(-2).captions.instruction, 'Local preview correction');
  assert.equal(savedHistory.history.at(-1).revert, true);
  assert.equal(savedHistory.instruction, savedHistory.original.instruction);
  assert.equal(savedHistory.review_flag, false); assert.equal(savedHistory.crop, null);
  assert.equal(savedHistory.history.at(-2).captions.review_flag, true);
  assert.equal(savedHistory.history.at(-2).captions.review_reason, 'Hands are obscured; please verify this action.');
  assert.deepEqual(savedHistory.history.at(-2).captions.crop, testCrop);
  assert.equal(await page.locator('#captionCompare').isHidden(), true);
  await page.locator('#compareBtn').click();
  await page.locator('#cmpAfter').selectOption(String(version + 1));
  assert.match(await page.locator('#cmpContent').innerText(), /Local preview correction/);
  assert.match(await page.locator('#cmpMeta').innerText(), /Mock worker/);
  await page.locator('#cmpBefore').selectOption(String(version + 1));
  assert.equal(await page.locator('#cmpCount').textContent(), 'No changes');
  await page.locator('#cmpBefore').selectOption('0');
  await page.locator('#captionCompare').screenshot({ path: path.join(state, 'captioning-data-comparison.png') });
  await page.locator('#cmpUnchanged').check();
  const jump = page.locator('#cmpContent button[data-t]').first();
  const target = Number(await jump.getAttribute('data-t')); await jump.click();
  assert.ok(Math.abs(await page.evaluate(() => document.querySelector('video').currentTime) - target) < 1);
  await page.evaluate(() => document.querySelector('video').pause());
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#captionSettingsBtn').click();
  await page.waitForFunction(() => {
    const panel = document.querySelector('#captionSettings'), box = panel.getBoundingClientRect();
    return panel.matches(':popover-open') && box.left >= 0 && box.right <= innerWidth && box.top >= 0 && box.bottom <= innerHeight;
  });
  await setCaptionWidth(20); assert.ok(await captionsInside());
  await setCaptionWidth(100); assert.ok(await captionsInside());
  await setCaptionWidth(94);
  assert.ok(await page.locator('#captionSettings').evaluate(panel => panel.scrollWidth <= panel.clientWidth + 1));
  await page.locator('#captionSettings').screenshot({ path: path.join(state, 'captioning-data-settings-mobile.png') });
  await page.keyboard.press('Escape');
  await page.locator('#compareBtn').click(); await page.locator('#compareBtn').click();
  await page.waitForFunction(() => document.body.classList.contains('noside'));
  assert.equal(await page.locator('#cmpContent td').first().evaluate(element => getComputedStyle(element).display), 'block');
  const mobile = await mediaLayout();
  assert.ok(mobile.comparison.y >= mobile.video.bottom + 10);
  assert.ok(await page.locator('#captionCompare').evaluate(element => element.scrollWidth <= element.clientWidth + 1));
  await page.locator('#cmpUnchanged').uncheck();
  await page.locator('#captionCompare').screenshot({ path: path.join(state, 'captioning-data-comparison-mobile.png') });
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.screenshot({ path: path.join(state, 'captioning-data-preview.png'), fullPage: true });
  await page.locator('#logout').click(); await page.locator('#login-view').waitFor();
  assert.equal((await context.request.get(`${base}/captioning_data/video?p=${encodeURIComponent(id)}`)).status(), 401);
  await page.locator('#identifier').fill('admin'); await page.locator('#password').fill('preview-password'); await page.locator('#login-button').click();
  await page.locator('#library-view').waitFor(); await page.locator('.recording-row').first().waitFor();
  await page.getByRole('link', { name: 'Open captioning_data' }).click(); await page.locator('#edSave').waitFor();
  await checkLandingDefaults();
  await checkQAProgress();
  await page.getByRole('button', { name: 'sign out', exact: true }).click(); await page.locator('#login-view').waitFor();
  for (const name of ['caption_data_admin', 'caption_data_reviewer']) {
    const response = await context.request.post(`${base}/api/auth/web/login`, { data: { email: name, password: 'preview-password' } });
    assert.equal(response.status(), 200); assert.deepEqual((await response.json()).roles, [name, 'worker']);
    const responseData = await context.request.get(`${base}/captioning_data/api/episodes`);
    assert.equal(responseData.status(), 200);
    assert.equal((await responseData.json()).user.role, name === 'caption_data_admin' ? 'admin' : 'reviewer');
    assert.equal((await context.request.get(`${base}/api/admin/videos`)).status(), 403);
    await page.goto(`${base}/captioning_data/`);
    await checkLandingDefaults();
    await checkQAProgress();
    await page.getByRole('button', { name: 'Flag for Review', exact: true }).click();
    assert.equal(await page.evaluate(() => EDIT.review_flag), true);
    await page.keyboard.press('Control+z');
  }
  assert.deepEqual(errors, []);
  console.log('PASS: mock login/roles; reviewer QA hides admin rows/totals; assigned landing/reload and collapsed comparison defaults; real video; restored control order; caption settings size/width/background, wrapping, native cue width, persistence, dismissal and mobile bounds; selected annotation always visible; inline parent subtask/instruction editing, correct target, child preserved, live comparison/caption sync, undo, typing isolation, mobile field and saved history; Qwen header saw sentence, unclipped desktop/mobile cards and visibility; Accept suggestion for subtask/instruction/parent, correct target, live sync, undo, draft-only and view-only behavior; manual timeline/table subtask selection, level-specific E/P, removed O; Enter/Up editing and live caption sync; caption drag, bounds, persistence, resize and F fullscreen; Space playback, trim/extend, undo and typing isolation; isolated corrections; before/after drafts, timing, text safety, saved/reverted history and responsive layout; admin navigation; logout.');
})().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => {
  try { if (restoreCaptions) await restoreCaptions(); }
  catch (error) { console.error(error); process.exitCode = 1; }
  finally { if (browser) await browser.close(); }
});
